[package]
name = "inkanim"
version = "0.4.0"
edition = "2021"
authors = ["Roms1383"]
license = "MIT OR Apache-2.0"
keywords = ["cli", "utils", "wolvenkit", "inkanim", "inkwidget"]
description = "CLI tool to quickly extract infos from JSON exports of .inkwidget and .inkanim"
categories = ["command-line-utilities"]
repository = "https://github.com/cyb3rpsych0s1s/inkanim"
exclude = [".vscode/*", ".idea/*", "screenshots/*", "*.json", ".github/*"]

[[bin]]
name = "inkanim"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkanim-macros = { path = "./macros"}
enum_dispatch = "0.3.13"
serde = { version = "1.0.213", features = ["derive"] }
serde-aux = "4.5.0"
serde_json = "1.0.132"
chrono = { version = "0.4.38", default-features = false, features = [
  "clock",
  "std",
  "serde",
] }
clap = { version = "4.5.20", features = ["derive"] }
const-str = "0.5.6"
convert_case = "0.6.0"
red4ext-rs = { git = "https://github.com/jac3km4/red4ext-rs.git", rev = "v0.9.1" }
term-table = "1.4.0"
