[package]
name = "cargo-inkanim"
version = "0.2.1"
edition = "2021"
authors = ["Roms1383"]
license = "MIT OR Apache-2.0"
keywords = ["cli", "utils", "wolvenkit", "inkanim", "inkwidget"]
description = "CLI tool to quickly extract infos from JSON exports of .inkwidget and .inkanim"
categories = ["command-line-utilities"]
repository = "https://github.com/cyb3rpsych0s1s/inkanim-utils"
exclude = [".vscode/*", ".idea/*", "screenshots/*", "*.json"]

[[bin]]
name = "inkanim"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde-aux = "4.1.2"
serde_json = "1"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive"] }
term-table = "1.3.2"
