[package]
name = "cargo-inkanim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde-aux = "4.1.2"
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive"] }
term-table = "1.3.2"
